# coding: utf-8

"""
    Gemma RESTful API

    This website documents the usage of the [Gemma RESTful API](https://gemma.msl.ubc.ca/rest/v2/). Here you can find example script usage of the API, as well as graphical interface for each endpoint, with description of its parameters and the endpoint URL.  Use of this webpage and the Gemma Web services, including the REST API, is subject to [these terms and conditions](https://pavlidislab.github.io/Gemma/terms.html). Please read these in full before continuing to use this webpage or any other part of the Gemma system.  You can [consult the CHANGELOG.md file](https://gemma.msl.ubc.ca/resources/restapidocs/CHANGELOG.md) to view  release notes and recent changes to the Gemma RESTful API.   # noqa: E501

    OpenAPI spec version: 2.9.4
    Contact: pavlab-support@msl.ubc.ca
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BioMaterialFactorValueAssignment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bio_material_id': 'int',
        'bio_material_name': 'str',
        'factor_value_ids': 'list[int]'
    }

    attribute_map = {
        'bio_material_id': 'bioMaterialId',
        'bio_material_name': 'bioMaterialName',
        'factor_value_ids': 'factorValueIds'
    }

    def __init__(self, bio_material_id=None, bio_material_name=None, factor_value_ids=None):  # noqa: E501
        """BioMaterialFactorValueAssignment - a model defined in Swagger"""  # noqa: E501
        self._bio_material_id = None
        self._bio_material_name = None
        self._factor_value_ids = None
        self.discriminator = None
        if bio_material_id is not None:
            self.bio_material_id = bio_material_id
        if bio_material_name is not None:
            self.bio_material_name = bio_material_name
        if factor_value_ids is not None:
            self.factor_value_ids = factor_value_ids

    @property
    def bio_material_id(self):
        """Gets the bio_material_id of this BioMaterialFactorValueAssignment.  # noqa: E501


        :return: The bio_material_id of this BioMaterialFactorValueAssignment.  # noqa: E501
        :rtype: int
        """
        return self._bio_material_id

    @bio_material_id.setter
    def bio_material_id(self, bio_material_id):
        """Sets the bio_material_id of this BioMaterialFactorValueAssignment.


        :param bio_material_id: The bio_material_id of this BioMaterialFactorValueAssignment.  # noqa: E501
        :type: int
        """

        self._bio_material_id = bio_material_id

    @property
    def bio_material_name(self):
        """Gets the bio_material_name of this BioMaterialFactorValueAssignment.  # noqa: E501


        :return: The bio_material_name of this BioMaterialFactorValueAssignment.  # noqa: E501
        :rtype: str
        """
        return self._bio_material_name

    @bio_material_name.setter
    def bio_material_name(self, bio_material_name):
        """Sets the bio_material_name of this BioMaterialFactorValueAssignment.


        :param bio_material_name: The bio_material_name of this BioMaterialFactorValueAssignment.  # noqa: E501
        :type: str
        """

        self._bio_material_name = bio_material_name

    @property
    def factor_value_ids(self):
        """Gets the factor_value_ids of this BioMaterialFactorValueAssignment.  # noqa: E501


        :return: The factor_value_ids of this BioMaterialFactorValueAssignment.  # noqa: E501
        :rtype: list[int]
        """
        return self._factor_value_ids

    @factor_value_ids.setter
    def factor_value_ids(self, factor_value_ids):
        """Sets the factor_value_ids of this BioMaterialFactorValueAssignment.


        :param factor_value_ids: The factor_value_ids of this BioMaterialFactorValueAssignment.  # noqa: E501
        :type: list[int]
        """

        self._factor_value_ids = factor_value_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BioMaterialFactorValueAssignment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BioMaterialFactorValueAssignment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
