# coding: utf-8

"""
    Gemma RESTful API

    This website documents the usage of the [Gemma RESTful API](https://gemma.msl.ubc.ca/rest/v2/). Here you can find example script usage of the API, as well as graphical interface for each endpoint, with description of its parameters and the endpoint URL.  Use of this webpage and the Gemma Web services, including the REST API, is subject to [these terms and conditions](https://pavlidislab.github.io/Gemma/terms.html). Please read these in full before continuing to use this webpage or any other part of the Gemma system.  You can [consult the CHANGELOG.md file](https://gemma.msl.ubc.ca/resources/restapidocs/CHANGELOG.md) to view  release notes and recent changes to the Gemma RESTful API.   # noqa: E501

    OpenAPI spec version: 2.9.4
    Contact: pavlab-support@msl.ubc.ca
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CurationDetailsUpdateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'troubled': 'bool',
        'needs_attention': 'bool',
        'curation_note': 'str',
        'note': 'str'
    }

    attribute_map = {
        'troubled': 'troubled',
        'needs_attention': 'needsAttention',
        'curation_note': 'curationNote',
        'note': 'note'
    }

    def __init__(self, troubled=None, needs_attention=None, curation_note=None, note=None):  # noqa: E501
        """CurationDetailsUpdateRequest - a model defined in Swagger"""  # noqa: E501
        self._troubled = None
        self._needs_attention = None
        self._curation_note = None
        self._note = None
        self.discriminator = None
        if troubled is not None:
            self.troubled = troubled
        if needs_attention is not None:
            self.needs_attention = needs_attention
        if curation_note is not None:
            self.curation_note = curation_note
        if note is not None:
            self.note = note

    @property
    def troubled(self):
        """Gets the troubled of this CurationDetailsUpdateRequest.  # noqa: E501


        :return: The troubled of this CurationDetailsUpdateRequest.  # noqa: E501
        :rtype: bool
        """
        return self._troubled

    @troubled.setter
    def troubled(self, troubled):
        """Sets the troubled of this CurationDetailsUpdateRequest.


        :param troubled: The troubled of this CurationDetailsUpdateRequest.  # noqa: E501
        :type: bool
        """

        self._troubled = troubled

    @property
    def needs_attention(self):
        """Gets the needs_attention of this CurationDetailsUpdateRequest.  # noqa: E501


        :return: The needs_attention of this CurationDetailsUpdateRequest.  # noqa: E501
        :rtype: bool
        """
        return self._needs_attention

    @needs_attention.setter
    def needs_attention(self, needs_attention):
        """Sets the needs_attention of this CurationDetailsUpdateRequest.


        :param needs_attention: The needs_attention of this CurationDetailsUpdateRequest.  # noqa: E501
        :type: bool
        """

        self._needs_attention = needs_attention

    @property
    def curation_note(self):
        """Gets the curation_note of this CurationDetailsUpdateRequest.  # noqa: E501


        :return: The curation_note of this CurationDetailsUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._curation_note

    @curation_note.setter
    def curation_note(self, curation_note):
        """Sets the curation_note of this CurationDetailsUpdateRequest.


        :param curation_note: The curation_note of this CurationDetailsUpdateRequest.  # noqa: E501
        :type: str
        """

        self._curation_note = curation_note

    @property
    def note(self):
        """Gets the note of this CurationDetailsUpdateRequest.  # noqa: E501


        :return: The note of this CurationDetailsUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this CurationDetailsUpdateRequest.


        :param note: The note of this CurationDetailsUpdateRequest.  # noqa: E501
        :type: str
        """

        self._note = note

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CurationDetailsUpdateRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CurationDetailsUpdateRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
