# coding: utf-8

"""
    Gemma RESTful API

    This website documents the usage of the [Gemma REST API](https://gemma.msl.ubc.ca/rest/v2/). Here you can find example script usage of the API, as well as graphical interface for each endpoint, with description of its parameters and the endpoint URL.  The documentation of the underlying java code can be found [here](https://gemma.msl.ubc.ca/resources/apidocs/ubic/gemma/web/services/rest/package-summary.html). See the [links section](https://gemma.msl.ubc.ca/resources/restapidocs/#footer) in the footer of this page for other relevant links.  Use of this webpage and Gemma web services, including the REST API, is subject to [these terms and conditions](https://pavlidislab.github.io/Gemma/terms.html). Please read these in full before continuing to use this webpage or any other part of the Gemma system.   # noqa: E501

    OpenAPI spec version: 2.4.1
    Contact: pavlab-support@msl.ubc.ca
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DatabaseEntry(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'accession': 'str',
        'accession_version': 'str',
        'id': 'int',
        'external_database': 'ExternalDatabase',
        'uri': 'str'
    }

    attribute_map = {
        'accession': 'accession',
        'accession_version': 'accessionVersion',
        'id': 'id',
        'external_database': 'externalDatabase',
        'uri': 'uri'
    }

    def __init__(self, accession=None, accession_version=None, id=None, external_database=None, uri=None):  # noqa: E501
        """DatabaseEntry - a model defined in Swagger"""  # noqa: E501
        self._accession = None
        self._accession_version = None
        self._id = None
        self._external_database = None
        self._uri = None
        self.discriminator = None
        if accession is not None:
            self.accession = accession
        if accession_version is not None:
            self.accession_version = accession_version
        if id is not None:
            self.id = id
        if external_database is not None:
            self.external_database = external_database
        if uri is not None:
            self.uri = uri

    @property
    def accession(self):
        """Gets the accession of this DatabaseEntry.  # noqa: E501


        :return: The accession of this DatabaseEntry.  # noqa: E501
        :rtype: str
        """
        return self._accession

    @accession.setter
    def accession(self, accession):
        """Sets the accession of this DatabaseEntry.


        :param accession: The accession of this DatabaseEntry.  # noqa: E501
        :type: str
        """

        self._accession = accession

    @property
    def accession_version(self):
        """Gets the accession_version of this DatabaseEntry.  # noqa: E501


        :return: The accession_version of this DatabaseEntry.  # noqa: E501
        :rtype: str
        """
        return self._accession_version

    @accession_version.setter
    def accession_version(self, accession_version):
        """Sets the accession_version of this DatabaseEntry.


        :param accession_version: The accession_version of this DatabaseEntry.  # noqa: E501
        :type: str
        """

        self._accession_version = accession_version

    @property
    def id(self):
        """Gets the id of this DatabaseEntry.  # noqa: E501


        :return: The id of this DatabaseEntry.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DatabaseEntry.


        :param id: The id of this DatabaseEntry.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def external_database(self):
        """Gets the external_database of this DatabaseEntry.  # noqa: E501


        :return: The external_database of this DatabaseEntry.  # noqa: E501
        :rtype: ExternalDatabase
        """
        return self._external_database

    @external_database.setter
    def external_database(self, external_database):
        """Sets the external_database of this DatabaseEntry.


        :param external_database: The external_database of this DatabaseEntry.  # noqa: E501
        :type: ExternalDatabase
        """

        self._external_database = external_database

    @property
    def uri(self):
        """Gets the uri of this DatabaseEntry.  # noqa: E501


        :return: The uri of this DatabaseEntry.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this DatabaseEntry.


        :param uri: The uri of this DatabaseEntry.  # noqa: E501
        :type: str
        """

        self._uri = uri

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DatabaseEntry, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DatabaseEntry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
