# coding: utf-8

"""
    Gemma RESTful API

    This website documents the usage of the [Gemma RESTful API](https://gemma.msl.ubc.ca/rest/v2/). Here you can find example script usage of the API, as well as graphical interface for each endpoint, with description of its parameters and the endpoint URL.  Use of this webpage and the Gemma Web services, including the REST API, is subject to [these terms and conditions](https://pavlidislab.github.io/Gemma/terms.html). Please read these in full before continuing to use this webpage or any other part of the Gemma system.  You can [consult the CHANGELOG.md file](https://gemma.msl.ubc.ca/resources/restapidocs/CHANGELOG.md) to view  release notes and recent changes to the Gemma RESTful API.   # noqa: E501

    OpenAPI spec version: 2.9.4
    Contact: pavlab-support@msl.ubc.ca
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DifferentialAnalysisRunRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'factor_ids': 'list[int]',
        'include_interactions': 'bool',
        'subset_factor_id': 'int'
    }

    attribute_map = {
        'factor_ids': 'factorIds',
        'include_interactions': 'includeInteractions',
        'subset_factor_id': 'subsetFactorId'
    }

    def __init__(self, factor_ids=None, include_interactions=None, subset_factor_id=None):  # noqa: E501
        """DifferentialAnalysisRunRequest - a model defined in Swagger"""  # noqa: E501
        self._factor_ids = None
        self._include_interactions = None
        self._subset_factor_id = None
        self.discriminator = None
        if factor_ids is not None:
            self.factor_ids = factor_ids
        if include_interactions is not None:
            self.include_interactions = include_interactions
        if subset_factor_id is not None:
            self.subset_factor_id = subset_factor_id

    @property
    def factor_ids(self):
        """Gets the factor_ids of this DifferentialAnalysisRunRequest.  # noqa: E501


        :return: The factor_ids of this DifferentialAnalysisRunRequest.  # noqa: E501
        :rtype: list[int]
        """
        return self._factor_ids

    @factor_ids.setter
    def factor_ids(self, factor_ids):
        """Sets the factor_ids of this DifferentialAnalysisRunRequest.


        :param factor_ids: The factor_ids of this DifferentialAnalysisRunRequest.  # noqa: E501
        :type: list[int]
        """

        self._factor_ids = factor_ids

    @property
    def include_interactions(self):
        """Gets the include_interactions of this DifferentialAnalysisRunRequest.  # noqa: E501


        :return: The include_interactions of this DifferentialAnalysisRunRequest.  # noqa: E501
        :rtype: bool
        """
        return self._include_interactions

    @include_interactions.setter
    def include_interactions(self, include_interactions):
        """Sets the include_interactions of this DifferentialAnalysisRunRequest.


        :param include_interactions: The include_interactions of this DifferentialAnalysisRunRequest.  # noqa: E501
        :type: bool
        """

        self._include_interactions = include_interactions

    @property
    def subset_factor_id(self):
        """Gets the subset_factor_id of this DifferentialAnalysisRunRequest.  # noqa: E501


        :return: The subset_factor_id of this DifferentialAnalysisRunRequest.  # noqa: E501
        :rtype: int
        """
        return self._subset_factor_id

    @subset_factor_id.setter
    def subset_factor_id(self, subset_factor_id):
        """Sets the subset_factor_id of this DifferentialAnalysisRunRequest.


        :param subset_factor_id: The subset_factor_id of this DifferentialAnalysisRunRequest.  # noqa: E501
        :type: int
        """

        self._subset_factor_id = subset_factor_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DifferentialAnalysisRunRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DifferentialAnalysisRunRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
