# coding: utf-8

"""
    Gemma RESTful API

    This website documents the usage of the [Gemma REST API](https://gemma.msl.ubc.ca/rest/v2/). Here you can find example script usage of the API, as well as graphical interface for each endpoint, with description of its parameters and the endpoint URL.  The documentation of the underlying java code can be found [here](https://gemma.msl.ubc.ca/resources/apidocs/ubic/gemma/web/services/rest/package-summary.html). See the [links section](https://gemma.msl.ubc.ca/resources/restapidocs/#footer) in the footer of this page for other relevant links.  Use of this webpage and Gemma web services, including the REST API, is subject to [these terms and conditions](https://pavlidislab.github.io/Gemma/terms.html). Please read these in full before continuing to use this webpage or any other part of the Gemma system.   # noqa: E501

    OpenAPI spec version: 2.4.1
    Contact: pavlab-support@msl.ubc.ca
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FactorValueBasicValueObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'characteristics': 'list[CharacteristicBasicValueObject]',
        'experimental_factor_category': 'CharacteristicBasicValueObject',
        'measurement': 'MeasurementValueObject',
        'fv_value': 'str',
        'fv_summary': 'str',
        'experimental_factor_id': 'int',
        'baseline': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'characteristics': 'characteristics',
        'experimental_factor_category': 'experimentalFactorCategory',
        'measurement': 'measurement',
        'fv_value': 'fvValue',
        'fv_summary': 'fvSummary',
        'experimental_factor_id': 'experimentalFactorId',
        'baseline': 'baseline'
    }

    def __init__(self, id=None, characteristics=None, experimental_factor_category=None, measurement=None, fv_value=None, fv_summary=None, experimental_factor_id=None, baseline=None):  # noqa: E501
        """FactorValueBasicValueObject - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._characteristics = None
        self._experimental_factor_category = None
        self._measurement = None
        self._fv_value = None
        self._fv_summary = None
        self._experimental_factor_id = None
        self._baseline = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if characteristics is not None:
            self.characteristics = characteristics
        if experimental_factor_category is not None:
            self.experimental_factor_category = experimental_factor_category
        if measurement is not None:
            self.measurement = measurement
        if fv_value is not None:
            self.fv_value = fv_value
        if fv_summary is not None:
            self.fv_summary = fv_summary
        if experimental_factor_id is not None:
            self.experimental_factor_id = experimental_factor_id
        if baseline is not None:
            self.baseline = baseline

    @property
    def id(self):
        """Gets the id of this FactorValueBasicValueObject.  # noqa: E501


        :return: The id of this FactorValueBasicValueObject.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FactorValueBasicValueObject.


        :param id: The id of this FactorValueBasicValueObject.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def characteristics(self):
        """Gets the characteristics of this FactorValueBasicValueObject.  # noqa: E501


        :return: The characteristics of this FactorValueBasicValueObject.  # noqa: E501
        :rtype: list[CharacteristicBasicValueObject]
        """
        return self._characteristics

    @characteristics.setter
    def characteristics(self, characteristics):
        """Sets the characteristics of this FactorValueBasicValueObject.


        :param characteristics: The characteristics of this FactorValueBasicValueObject.  # noqa: E501
        :type: list[CharacteristicBasicValueObject]
        """

        self._characteristics = characteristics

    @property
    def experimental_factor_category(self):
        """Gets the experimental_factor_category of this FactorValueBasicValueObject.  # noqa: E501


        :return: The experimental_factor_category of this FactorValueBasicValueObject.  # noqa: E501
        :rtype: CharacteristicBasicValueObject
        """
        return self._experimental_factor_category

    @experimental_factor_category.setter
    def experimental_factor_category(self, experimental_factor_category):
        """Sets the experimental_factor_category of this FactorValueBasicValueObject.


        :param experimental_factor_category: The experimental_factor_category of this FactorValueBasicValueObject.  # noqa: E501
        :type: CharacteristicBasicValueObject
        """

        self._experimental_factor_category = experimental_factor_category

    @property
    def measurement(self):
        """Gets the measurement of this FactorValueBasicValueObject.  # noqa: E501


        :return: The measurement of this FactorValueBasicValueObject.  # noqa: E501
        :rtype: MeasurementValueObject
        """
        return self._measurement

    @measurement.setter
    def measurement(self, measurement):
        """Sets the measurement of this FactorValueBasicValueObject.


        :param measurement: The measurement of this FactorValueBasicValueObject.  # noqa: E501
        :type: MeasurementValueObject
        """

        self._measurement = measurement

    @property
    def fv_value(self):
        """Gets the fv_value of this FactorValueBasicValueObject.  # noqa: E501


        :return: The fv_value of this FactorValueBasicValueObject.  # noqa: E501
        :rtype: str
        """
        return self._fv_value

    @fv_value.setter
    def fv_value(self, fv_value):
        """Sets the fv_value of this FactorValueBasicValueObject.


        :param fv_value: The fv_value of this FactorValueBasicValueObject.  # noqa: E501
        :type: str
        """

        self._fv_value = fv_value

    @property
    def fv_summary(self):
        """Gets the fv_summary of this FactorValueBasicValueObject.  # noqa: E501


        :return: The fv_summary of this FactorValueBasicValueObject.  # noqa: E501
        :rtype: str
        """
        return self._fv_summary

    @fv_summary.setter
    def fv_summary(self, fv_summary):
        """Sets the fv_summary of this FactorValueBasicValueObject.


        :param fv_summary: The fv_summary of this FactorValueBasicValueObject.  # noqa: E501
        :type: str
        """

        self._fv_summary = fv_summary

    @property
    def experimental_factor_id(self):
        """Gets the experimental_factor_id of this FactorValueBasicValueObject.  # noqa: E501


        :return: The experimental_factor_id of this FactorValueBasicValueObject.  # noqa: E501
        :rtype: int
        """
        return self._experimental_factor_id

    @experimental_factor_id.setter
    def experimental_factor_id(self, experimental_factor_id):
        """Sets the experimental_factor_id of this FactorValueBasicValueObject.


        :param experimental_factor_id: The experimental_factor_id of this FactorValueBasicValueObject.  # noqa: E501
        :type: int
        """

        self._experimental_factor_id = experimental_factor_id

    @property
    def baseline(self):
        """Gets the baseline of this FactorValueBasicValueObject.  # noqa: E501


        :return: The baseline of this FactorValueBasicValueObject.  # noqa: E501
        :rtype: bool
        """
        return self._baseline

    @baseline.setter
    def baseline(self, baseline):
        """Sets the baseline of this FactorValueBasicValueObject.


        :param baseline: The baseline of this FactorValueBasicValueObject.  # noqa: E501
        :type: bool
        """

        self._baseline = baseline

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FactorValueBasicValueObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FactorValueBasicValueObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
