# coding: utf-8

"""
    Gemma RESTful API

    This website documents the usage of the [Gemma RESTful API](https://gemma.msl.ubc.ca/rest/v2/). Here you can find example script usage of the API, as well as graphical interface for each endpoint, with description of its parameters and the endpoint URL.  Use of this webpage and the Gemma Web services, including the REST API, is subject to [these terms and conditions](https://pavlidislab.github.io/Gemma/terms.html). Please read these in full before continuing to use this webpage or any other part of the Gemma system.  You can [consult the CHANGELOG.md file](https://gemma.msl.ubc.ca/resources/restapidocs/CHANGELOG.md) to view  release notes and recent changes to the Gemma RESTful API.   # noqa: E501

    OpenAPI spec version: 2.9.4
    Contact: pavlab-support@msl.ubc.ca
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TaskStatusValueObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'task_id': 'str',
        'experiment_id': 'int',
        'step': 'str',
        'status': 'str',
        'submitted_at': 'datetime',
        'started_at': 'datetime',
        'completed_at': 'datetime',
        'message': 'str'
    }

    attribute_map = {
        'task_id': 'taskId',
        'experiment_id': 'experimentId',
        'step': 'step',
        'status': 'status',
        'submitted_at': 'submittedAt',
        'started_at': 'startedAt',
        'completed_at': 'completedAt',
        'message': 'message'
    }

    def __init__(self, task_id=None, experiment_id=None, step=None, status=None, submitted_at=None, started_at=None, completed_at=None, message=None):  # noqa: E501
        """TaskStatusValueObject - a model defined in Swagger"""  # noqa: E501
        self._task_id = None
        self._experiment_id = None
        self._step = None
        self._status = None
        self._submitted_at = None
        self._started_at = None
        self._completed_at = None
        self._message = None
        self.discriminator = None
        if task_id is not None:
            self.task_id = task_id
        if experiment_id is not None:
            self.experiment_id = experiment_id
        if step is not None:
            self.step = step
        if status is not None:
            self.status = status
        if submitted_at is not None:
            self.submitted_at = submitted_at
        if started_at is not None:
            self.started_at = started_at
        if completed_at is not None:
            self.completed_at = completed_at
        if message is not None:
            self.message = message

    @property
    def task_id(self):
        """Gets the task_id of this TaskStatusValueObject.  # noqa: E501


        :return: The task_id of this TaskStatusValueObject.  # noqa: E501
        :rtype: str
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id):
        """Sets the task_id of this TaskStatusValueObject.


        :param task_id: The task_id of this TaskStatusValueObject.  # noqa: E501
        :type: str
        """

        self._task_id = task_id

    @property
    def experiment_id(self):
        """Gets the experiment_id of this TaskStatusValueObject.  # noqa: E501


        :return: The experiment_id of this TaskStatusValueObject.  # noqa: E501
        :rtype: int
        """
        return self._experiment_id

    @experiment_id.setter
    def experiment_id(self, experiment_id):
        """Sets the experiment_id of this TaskStatusValueObject.


        :param experiment_id: The experiment_id of this TaskStatusValueObject.  # noqa: E501
        :type: int
        """

        self._experiment_id = experiment_id

    @property
    def step(self):
        """Gets the step of this TaskStatusValueObject.  # noqa: E501


        :return: The step of this TaskStatusValueObject.  # noqa: E501
        :rtype: str
        """
        return self._step

    @step.setter
    def step(self, step):
        """Sets the step of this TaskStatusValueObject.


        :param step: The step of this TaskStatusValueObject.  # noqa: E501
        :type: str
        """

        self._step = step

    @property
    def status(self):
        """Gets the status of this TaskStatusValueObject.  # noqa: E501


        :return: The status of this TaskStatusValueObject.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this TaskStatusValueObject.


        :param status: The status of this TaskStatusValueObject.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def submitted_at(self):
        """Gets the submitted_at of this TaskStatusValueObject.  # noqa: E501


        :return: The submitted_at of this TaskStatusValueObject.  # noqa: E501
        :rtype: datetime
        """
        return self._submitted_at

    @submitted_at.setter
    def submitted_at(self, submitted_at):
        """Sets the submitted_at of this TaskStatusValueObject.


        :param submitted_at: The submitted_at of this TaskStatusValueObject.  # noqa: E501
        :type: datetime
        """

        self._submitted_at = submitted_at

    @property
    def started_at(self):
        """Gets the started_at of this TaskStatusValueObject.  # noqa: E501


        :return: The started_at of this TaskStatusValueObject.  # noqa: E501
        :rtype: datetime
        """
        return self._started_at

    @started_at.setter
    def started_at(self, started_at):
        """Sets the started_at of this TaskStatusValueObject.


        :param started_at: The started_at of this TaskStatusValueObject.  # noqa: E501
        :type: datetime
        """

        self._started_at = started_at

    @property
    def completed_at(self):
        """Gets the completed_at of this TaskStatusValueObject.  # noqa: E501


        :return: The completed_at of this TaskStatusValueObject.  # noqa: E501
        :rtype: datetime
        """
        return self._completed_at

    @completed_at.setter
    def completed_at(self, completed_at):
        """Sets the completed_at of this TaskStatusValueObject.


        :param completed_at: The completed_at of this TaskStatusValueObject.  # noqa: E501
        :type: datetime
        """

        self._completed_at = completed_at

    @property
    def message(self):
        """Gets the message of this TaskStatusValueObject.  # noqa: E501


        :return: The message of this TaskStatusValueObject.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this TaskStatusValueObject.


        :param message: The message of this TaskStatusValueObject.  # noqa: E501
        :type: str
        """

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TaskStatusValueObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TaskStatusValueObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
